### ISSUE TITLE
SSH admin key "Wait for nodes to be contactable" task fails without python package, then hangs with it

### ISSUE THREAD

**Issue by psmallwood-ot** [csmart/ansible-role-swift#2]
On first try, it failed with:

fatal: [swift-admin -> swift-admin]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ swift_cluster_subnet | next_nth_usable(server_ip) }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The next_nth_usable filter requires python's netaddr be installed on the ansible controller"}

But after installing both netaddr packages available on the CentOS 7 (not stream) machine that is executing Ansible, it then gets to the step of waiting, and hangs for over 10 minutes.

Is there a way to increase logging of the steps in there? I've edited ansible.cfg and enabled logging, but it doesn't log anything after waiting for nodes.

**Comment by csmart** [comment]
Hi @psmallwood-ot, ahh yes, thanks for that. I will see if I turn that into a check so that it fails early. I might even be able to install it as part of the role before it gets to that task.

So the step that's failing, is that the task "Wait for nodes to be contactable via SSH" or a different one? 

Are you using pre-configured nodes and are they CentOS 8 Stream?

if it's that one, then the task should be being run on the Swift admin bnox, where it's waiting for port 22 to be available on the nodes using their `swift_cluster_ip`.

```yaml
    - name: Wait for nodes to be contactable via SSH                             
      wait_for:                                                                  
        port: 22                                                                 
        host: "{{ swift_cluster_ip }}"                                           
        search_regex: OpenSSH                                                    
        timeout: 600                                                             
      delegate_to: swift-admin                                                   
```

I'm not sure if adding `-vvv` options to your playbook will show any extra debugging for you, but are you able to do a manual check? Maybe try logging on to the swift-admin box and then see if you can SSH to the other nodes using the cluster IP that you expect? That might help us to work out whether the swift-admin box is not able to talk to them, whether SSH isn't listening on that IP, or perhaps the nodes you're using don't match the "OpenSSH".

Please let me know how you go and then I'll see if I can replicate it.

Cheers,
-c
